FROM python:3.11-slim-buster

WORKDIR /users

RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2

COPY requirements.txt ./

RUN pip install -r requirements.txt

EXPOSE ${PORT}

COPY . .

CMD ["sh", "-c","DATABASE_URL=postgresql://user:1234@sql:5432/users", "PYTHONPATH=./app", "pytest"]